---
# Source: nginx/templates/nginx-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: nginx-1-nginx-secret
  labels:
    app.kubernetes.io/name: nginx-1
    app.kubernetes.io/component: nginx-server
data:
  https1.cert: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN2RENDQWFRQ0NRRGt0SzRETEtGeVlUQU5CZ2txaGtpRzl3MEJBUXNGQURBZ01RNHdEQVlEVlFRRERBVnUKWjJsdWVERU9NQXdHQTFVRUNnd0ZibWRwYm5nd0hoY05NakF3TnpJMU1UZzBPRFF6V2hjTk1qRXdOekkxTVRnMApPRFF6V2pBZ01RNHdEQVlEVlFRRERBVnVaMmx1ZURFT01Bd0dBMVVFQ2d3RmJtZHBibmd3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUR5NElNRStmYnpMUEswV3k5dldTZCtLdVFaSy8rTHBVY1gKWFBOdVgrSUhwZnV2d0hVcFNmVkgvb1M3TUVIVkFmNTUwTVJCYllaZHU0M2puemV0SDhVczZwRXNGS2ZCQ3lRUQpVNVdOcXJrcjY1bXBrMVhRdnY3OHRVOVpXcEZmYzlzSlZkK1BrTmMwTHVPQ2J2WGJkanRWZUFSWGFTNnVzZ05SCkZLWlgxaGdFNVM2dnRydFpIR1Bjd1dwZXBQejdWcG9nQndTZGpmS2RlaksveWVDalZRNDE3cXJoeXpsay9GVmEKTDFpSWJNSE1KblVSMU9JUU15NmxNdnllZGw4Q3pXMS9CTjFWVVhFak12SnpLODhEUFFyWnlGcFNjUFIxSmN2QgpKZUhoOEVkZHgwa3ZSV3VNeEpxMWhwaVJCUWZLRFNDMkVuU0dpRkRxRjFGRk1oVmZlUGY5QWdNQkFBRXdEUVlKCktvWklodmNOQVFFTEJRQURnZ0VCQU9IenRtdWJ0Q1FySmlHSEZMOVdpL0JFSFBpWFJpUlVBZGl4cmZ1bWwwUFEKM2hHdUU1aVIxRThMWCtaSU8zUFRvZnZTT3hiMzlTM1N1VjcySDRQYzdlU2UyTlV0ekRLckRoQ29nL3Era3piTwoxUkdJMWxPM1RKbU1qdFFhTDdXZVJUaWxsMkVrRTNXVjBjVEZKcm5Dd3Q4aHlYK25KVm1mWE1MeDVBNHdkNnE0CmladWsxYTNwczlITktEWE05eE9Dd0pVejNuanVSWWR3UlRpNXVieERkMjVramRVdjlkL0NURkFQOVRIWGpTRkYKeWw4WlB0Q1RaWENxck1JektFdERxK3kyVnhMaUtuVGYwOFJWcGgyWXpUS1J0d21Tc0NwdlY0UzUxTjU1cVI5aApTUldseldmMTFNbHBMNlZGUS83RzdFb1pQQTVac0MwMXl1d0tBUW9uSWxNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  https1.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV3QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktvd2dnU21BZ0VBQW9JQkFRRHk0SU1FK2ZiekxQSzAKV3k5dldTZCtLdVFaSy8rTHBVY1hYUE51WCtJSHBmdXZ3SFVwU2ZWSC9vUzdNRUhWQWY1NTBNUkJiWVpkdTQzagpuemV0SDhVczZwRXNGS2ZCQ3lRUVU1V05xcmtyNjVtcGsxWFF2djc4dFU5WldwRmZjOXNKVmQrUGtOYzBMdU9DCmJ2WGJkanRWZUFSWGFTNnVzZ05SRktaWDFoZ0U1UzZ2dHJ0WkhHUGN3V3BlcFB6N1Zwb2dCd1NkamZLZGVqSy8KeWVDalZRNDE3cXJoeXpsay9GVmFMMWlJYk1ITUpuVVIxT0lRTXk2bE12eWVkbDhDelcxL0JOMVZVWEVqTXZKegpLODhEUFFyWnlGcFNjUFIxSmN2QkplSGg4RWRkeDBrdlJXdU14SnExaHBpUkJRZktEU0MyRW5TR2lGRHFGMUZGCk1oVmZlUGY5QWdNQkFBRUNnZ0VCQUp0QjFiOUtvd2hVUlZueHFHTC9sUFZjS2EvRnBuZjRVWGVuM1oxREFkUnQKMEhSTERSbzF3dXdnMFd4dnJzV2huckQwT1dDeHlPRUdVZStlQ2hOTGFkb0tvSDZUUGFGem83d2tFa2diU0gvQQovZHVlNlk2bGFZN1Z3RUdZV2JHdzkrWUIxUVdMUzJaNlNzbEljVFczWUxxRUhCSmNsSkRzRHA2NEdwV3ZzRzcvCmE0amEvSUxMK085YXJGbS8zSC8wZWdMUW9lN0NUUi9aZ1ZlbmpWVGdpeHExWFBTWit3Vk5QdWt0TkxMRnREdVYKYUFSdXRSMysxK20wbEZpWjJJTTA0SHl1ekJwdmdweUJJR1N6dG5GL0U5eVlMVFBmYysrdm5OVU9vQ2dhbk5LRQorYk9GV1EyRGN6MmJqNWxNVVQrYkg3anY3aDIyNm9OT2pxWDgwY0Z6aGtFQ2dZRUErdlgxT0Y1dnArRHI0V2VVClhrWnNocGQvM3NmUkpFOEtuaUZaMUtDd3RTM08xS2NqcXJwZGNxMU5EL3hseVU4dzVUYzRqSlN1OEhBenpiKzgKdmUxczFpNGQyRDhBV20zSTVyb0paUzhpSks4KzlsYzhFQlA5Q3VlZXpGbnllT2pTRzNjdmZ3TDBNM2dwdEQ5WgpRZnVBMy9NNlZNU3NoTnFGVG9BK3JKYXhaaGtDZ1lFQTk4RC8vYXVjc0hteEVZTG1aTTJlc2dZUzJGci9VOFpHCk4yQVhYT3pRd3Bxa2xqME9jRTBITkpGY1hPaG4zZ3VvVm56eEtqUFd1YW5YZ3lwY2wvOGpZM25TNHZVc3hkUHUKdHdmTmExbEx3NHVQdnpOdTBvUm9najkrVTRObld6b3k2RG5DZVNudlMwNjVkZ1F3TmpnUWdRVTdpYjRqRWducQo1Wkc4Q1R5QjlZVUNnWUVBdFpQa1cyYW9ydlRrZG5CMVAwa0JHTmpnNGhYOVVxSUY4cWY2MFFkN0Uzd1RYSFdhCkx0c3M1ZDVTRmJEdkRKckpxKzhxY1R6YTNvaXdVcnZhR2ltQlIrNlNGWFp3RVAzQ0VINm1jWm1Ld0xRemdCVmEKRmVBQWhEVldCbEZHU1FsYmpCZk9PNzJ0WnRnWWhKd1pQczUwVHBVenJVV245WEFPWitBT2VOMkhlWEVDZ1lFQQp5Y0FvdGZHaHp6UEp0WERiSFFzMFI5UWFWSVVGbHJySFF5REU1YThTOE9YdFVVcTNEMHdxcWV3VlFyTWVvZnJzClFrSE1RWW1sT2R2TTI4c0xTOXRBZmlrZVNpTk5LbXZDNE5sQnRrRXBLVHZrK3RadlVJN3lhOTQ0aU5sZ3VURlQKY3poVjNVVUEwRnB6UEY5OHd5bzBobHcwZDU2V0FJS0MvaDhHK0o2RlZlRUNnWUVBam4rNUxmLy90WFFhS0ViWAptVWo4MURCdmJrMGtuMk1NRlZ3SmV5TzMwREJxUVFISDZ1NC9FL2RmSFp4ak5XVk5YM3hGeEZWV2tSdWRmbGhmCjF2ZmFIbG51RVU5WHhmaTFtSlZWMG5QK1lVVHYvdStTKytkaHQydkxhNzczYndlOUdCSG1Ubk5CTVB6N0FXdnIKUFJ6WnFtN2lDeGxtNWc5c2JKdXp4S2hnVG1JPQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
---
# Source: nginx/templates/nginx-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-1-nginx-configmap
  labels:
    app.kubernetes.io/name: nginx-1
    app.kubernetes.io/component: nginx-server
data:
  index.html: |
   <!DOCTYPE>
    <html>
     <head> <title>Web Server Application</title> </head>
     <body> <h1>Web site powered by NGINX</h1>
     <p>This page is under construction. Please come back soon!</p></body>
    </html>
  nginx-config.conf: |
   ssl_certificate      certs/https1.cert;
   ssl_certificate_key  certs/https1.key;
   server {
      listen 80;
      listen 443 ssl;
      listen 8080;
      server_name www.my-webserver.com;
      location / {
               index index.html;
               root /usr/share/nginx/html;
      }
      location /stub_status {
      stub_status on;
      access_log off;
      allow 127.0.0.1;
      deny all;
      }
      location = /favicon.ico {
               error_page 404 = @empty;
      }
      location @empty {
               empty_gif;
      }
    }
---
# Source: nginx/templates/nginx-services.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-1-nginx-prometheus-svc
  labels:
    app.kubernetes.io/name: nginx-1
    app.kubernetes.io/component: nginx-server
spec:
  clusterIP: None
  ports:
  - name: prometheus-port
    port: 9113
    protocol: TCP
  selector:
    app.kubernetes.io/name: nginx-1
    app.kubernetes.io/component: nginx-server
---
# Source: nginx/templates/nginx-services.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-1-nginx-svc
  labels:
    app.kubernetes.io/name: nginx-1
    app.kubernetes.io/component: nginx-server
spec:
  ports:
  - name: nginx-http-port
    port: 80
    protocol: TCP
  - name: nginx-https-port
    port: 443
    protocol: TCP
  selector:
    app.kubernetes.io/name: nginx-1
    app.kubernetes.io/component: nginx-server
  
  type: LoadBalancer
---
# Source: nginx/templates/nginx-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-1-nginx
  labels: &NginxDeploymentLabels
    app.kubernetes.io/name: nginx-1
    app.kubernetes.io/component: nginx-server
spec:
  selector:
    matchLabels: *NginxDeploymentLabels
  updateStrategy:
    type: RollingUpdate
  serviceName: nginx-1-nginx-svc
  replicas: 1
  volumeClaimTemplates:
  - metadata:
      name: nginx-1-nginx-pvc
      labels: *NginxDeploymentLabels
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      labels: *NginxDeploymentLabels
    spec:
      terminationGracePeriodSeconds: 180
      initContainers:
      # This init container is reponsible for creating default index html file
      - name: initialize-volume
        image: marketplace.gcr.io/google/nginx/debian9:1.15
        imagePullPolicy: Always
        command:
        - /bin/bash
        - -euc
        - |
          if [[ ! -f /usr/share/nginx/html/index.html ]]; then
          cat <<EOF >/usr/share/nginx/html/index.html
          <!DOCTYPE>
          <html>
            <head>
              <title>Web Server Application</title>
            </head>
            <body>
               <h1>Web site powered by NGINX</h1>
               <p>This page is under construction. Please come back soon!</p>
            </body>
          </html>
          EOF
          fi
        volumeMounts:
        - name: nginx-1-nginx-pvc
          mountPath: /usr/share/nginx/html
      containers:
      - name: nginx
        image: "marketplace.gcr.io/google/nginx:1.15"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: nginx
          containerPort: 80
          protocol: TCP
        - name: nginx-https
          containerPort: 443
          protocol: TCP
        - name: prometheus
          containerPort: 9113
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: nginx
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: nginx
          initialDelaySeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: nginx-1-nginx-pvc
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: certs
          mountPath: /etc/nginx/certs
          readOnly: true
      
      
      volumes:
      - name: certs
        secret:
          secretName: nginx-1-nginx-secret
      - name: nginx-config
        configMap:
          name: nginx-1-nginx-configmap
          items:
          - key: nginx-config.conf
            path: nginx-config.conf
---
# Source: nginx/templates/application.yaml
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "nginx-1"
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIIAAACCCAMAAAC93eDPAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAMAUExURQAAAACbAACbAACbAACbAACbAACbAACbAACbAACbAACbAACbAACYAACbAACbAACbAACbAACbAACbAACbAACbAACbAACWAACbAACZAACbAACaAACbAACbAACbAACaAACbAACbAACbAACbAACaAACaAACbAACZAACbAACbAACbAACbAACbAACaAACaAACbAACaAACbAACZAACbAACaAACaAACbAACaAACbAACbAACaAACaAACaAACaAACaAACbAACbAACaAACbAACbAACZAACbAACaAACbAACbAACYAACbAACaAACbAACZAACbAACbAACbAACaAACbAACbAACbAACbAACbAACaAACbAACbAACZAACaAACaAACbAACaAACaAACaAACbAACaAACbAACbAACbAACZAACaAACbAACaAACaAACbAACaAACaAACaAACaAACbAACbAACbAACaAACbAACbAACbAACaAACbAACaAACZAACaAACaAACbAACaAACaAACbAACbAACbAACbAACbAACaAACaAACaAACbAACbAACbAACaAACbAACaAACaAACbAACaAACaAACbAACaAACbAACbAACbAACbAACbAACbAACXAACZAACaAACbAACbAACbAACaAACbAACbAACbAACaAACbAACbAACbAACbAACbAACaAACbAACZAACaAACbAACbAACbAACbAACbAACaAACaAACaAACbAACaAACbAACbAACZAACaAACVAACbAACbAACaAACbAACbAACaAACaAACbAACbAACbAACbAACbAACbAACbAACaAACaAACbAACbAACaAACbAACbAACbAACbAACbAACaAACbAACZAACaAACZAACbAACbAACbAACbAACaAACZAACaAACbAACaAACbAACbAACbAACaAACaAACbAACbAACbAACaAACaAACbAACaAACbAACbAACaAACaAACaAACaAACaAACaAACaAACaAACbAACaAACaAACbAACbAACbAACaAACbANJeAvUAAAD/dFJOUwCoSvxPpP77+swo6wOmkD/1+HXx/YIB9wbOCL2j8Az5uYj0Hw3hDoHDwJ3qBxqgNewC8hc/9guPkUYkMDEz7Y0VyJwQsyOUyQSWOPMLgOJ8Qre/CO/dPM3LFCAv4y4ULOhQtqfeGT21DyLGWh5YG1MEylG6vIkSYUcJNE3PKnFt0Ce0ohYTSNjS5gqlSy1wTmKMIXdOrtrU2wIIKJOq7mCvrT4r54ff0eRtbBNEBXrpwlJcaKyGX8WbBUMCXZ5KeFxWUtZgmERDq5I3MtV5HeVl07g2GGkWYRKZJHRoRRUcsoyLjp9djlZkg4p7wZZze3SCETlbV3MlrGc6NdcuTyzHxewAAAU3SURBVHja7ZdXWFRHFIAPortLgprNbnYXgQWWtlQRaYYaBETpBFGjQqxgQSzRWGOJUWPsUROTGGONLZZ0Y3rvvffee+/XOzO3zC3Al5e8eP4Hdhpz/52dOXMuAIIgCIIgCIIgCIIgCIIgCIIgCIL8X+Q+Hh6x5GGPtrF3kG3VCqV2siYkiCPknoFKV3JNmmOjVyx4ZzeEF8ZoJnENSMj0vdhIy55LRtlD++oenVLsCB88AXKHCyKOA9v4via/2DZsmlzNqxY0RCxWRnZzCIL7frFws1tsv1jzhBWxZPDKl0h5jDhOCJmv6e8fYBGEwMFwK5s1bQzfOYT8g/sxqeZJFHTEKt/nNlItFgt3kkKqi5tk7VVscIC4wq5UWlyYrzGgbddDgzTryqf43+EsscXaTarNDdcrCO/LP0UvUuspFnrQpwWrcyxvkcaOjxYVwlh5WJ7S/+o4C21KB2XW0GkdKMSNNRgI1u+7UkjOsUhjk84Qq1PcrBKUK/W/ewXrt4SpCkJipbnC7RGkNyH+HEp8gJVU9//ZhcIrmfK8ZxKFa6JsrDZ8JO0eESYZlkRzCrZngs0UUuh+vXCI3Heojo6uO9Spwjt7BI0CZH0oOQwaTQwulQzGTgWm4HCSvw0PmCkcoYMLT6p7lZ4P5xFXJwpLF6rzMgXI2ig5nLcWLkuVDOouAEnhm6/px9AnjQq7x5Oeq6/lNusBOtfR2o4VXr+Bzrd1r11VAO9HVvbcyRMTnawUSQyYwrd96YMEf7ReIbiM7pkr+SMbl3MsISHBH0/C2UF/fb2/RqfgmU0f4fhsvY1TAG8vySFJWo9Zk0BROBva2MELi9MpZKTRfZyiiSnT+1DILzH9fJGbdAobfKQSWAWbNQoQk2Plj9VFpcArBH9HzaxV5RqFrJ10o77WdZznFDJG0UnHtUJ3rQLEXReoGoSeCxoF8H7MAsUnGoVf6NGKpIHIk7+5u4Z/xUjyT/vx4+1/aRRKB7FdJ66yXgHiyqwGA0UB3qtnsXcipxBMJxbW0VjzRVqgBsvfvwFkC06n0INXaGVxt3oXmCjAJilqC+n3gkEB5m9l57aUW4U2dRVq03UR0vmr2Ykoj6dr7aM31n9cBYAHC2hl+4+qQiU9XbYNYu/n+iA9ub+Zws8Oqhd1wkwhptO9INLvLRqKnXu37VJORG2BfCJ66y4rd5tJXHD9tI927pwDJgqdnwjK6kdozbcjQ1Eof0OOC56v9tgZLK5syTIq9Jzkp30hS8FEwZstxwXpc9YmgwK8HMm25A8VSnQcGStHx/LdhweIHJ5CW9IyTO6IFrZ9L38UTBS8n3YWHWUFGP00i+2B6h0RL+juiD/oTGXlJgoVNLhkvg0mCpUfyHdEM3dHRBsUYM1RNSdgCtGrtDfl1BvpdbLI7LJmGUB2solC5Zf8TdlkuClVBddit04BbrHy+ULV72QRLfdBhwrLisCooOQLM1i+0KTPF1QF6KNkO7LCnHpj1jRjQocKLzSDiYIhayrSZU2cAhSVSHNVNEotM316A/vdoFd4Qk7T1oCJgknuuFzJHcmNLhzkL5xFS6RtM0JqmLddr1CivDBE0ZRPLLSzr2lfxyfRc8nsz72pZNAhphn0MnKItO8YtUPpBpypNDQmaQ0K7lK6FojHN2IHSYqKyR6xZc/jZ3qWbN0tq5X3iHzT94jmFnv18/20F29GpM99x3r15eZElPZtqjBZ3TpVBY5suiZFUfut+2patTMteMh2LK+rtykEQRAEQRAEQRAEQRAEQRAEQRDk9OAURpCcjQcYD6YAAAAASUVORK5CYII=
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "click-to-deploy-containers", "product_id": "nginx", "partner_name": "Google Click to Deploy"}'
  labels:
    app.kubernetes.io/name: "nginx-1"
spec:
  descriptor:
    type: NGINX
    version: "1.15"
    description: |-
      NGINX is open-source software for web serving, reverse proxying,
      caching, load balancing, and media streaming.

      NGINX can also function as a proxy server for email (IMAP, POP3, and SMTP)
      and a reverse proxy and load balancer for HTTP, TCP, and UDP servers.

      If you would like to learn more about NGINX, please,
      visit [NGINX website](https://www.nginx.com/).

      # Support

      This image is built by Google. It is your responsibility to keep
      container images you run or store in your own repositories
      up to date with security patches.

      Community support for NGINX is available on
      [Stack Overflow](http://stackoverflow.com/questions/tagged/nginx/).

      Please report issues with this NGINX container image via
      the [GitHub Issue Tracker](https://github.com/GoogleCloudPlatform/nginx-docker/issues).
    maintainers:
    - name: Google Click to Deploy
      url: https://cloud.google.com/solutions/#click-to-deploy
    links:
    - description: 'User Guide: Google Click to Deploy NGINX'
      url: https://github.com/GoogleCloudPlatform/nginx-docker/blob/master/1/README.md
    - description: 'NGINX: Getting Started'
      url: https://www.nginx.com/resources/wiki/start/
    notes: |-
      # Configuring the web content of NGINX server

      Follow this instructions to upload web content to your Web Server:

      1. Navigate to a folder where directory containing your website is located
         (e.g. assuming that your web content is stored in `html` directory)
      1. Run the following command to copy the content of `html` directory to the Persistent Volume:
         ```
         kubectl cp html nginx-1-nginx-0:/usr/share/nginx -n default
         ```
      1. Set permissions so NGINX server has access to the newly uploaded `html` directory:
         ```
         kubectl exec nginx-1-nginx-0 -n default -- chmod -R a+r /usr/share/nginx/html
         ```
      # Configuring SSL certificate for NGINX server

      This version of NGINX application uses pre-generated certificate which is self-signed and is meant to be
      only a temporary solution just to exemplify SSL/TLS configuration.

      Generate a new self-signed certificate for your NGINX server using `openssl` command
      or use a signed certifcate that you already own.

      For example, if you would like to generate self-signed certifcate and private key
      you could run the following command:
      ```
      openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout https1.key -out https1.cert
      ```

      Configure your own certificate using the following command:
      ```
      export CERT_FILE=https1.cert
      export KEY_FILE=https1.key
      export APP_INSTANCE_NAME=<name of your NGINX instance, e.g. nginx-1>
      export NAMESPACE=<name of your Kurbernetes namespace, e.g. default>

      # using --dry-run option because we update existing secret resource
      # if we used kubectl create... for existing secret we would get an error
      kubectl --namespace default create secret generic nginx-1-nginx-secret \
        --from-file=$CERT_FILE --from-file=$KEY_FILE \
        --dry-run -o yaml | kubectl apply -f -
      ```
      where .cert is a file containing SSL certificate and .key file contains private part of it.

      Run these commands to restart all Pods without causing a downtime
      ```
      PODS=$(kubectl get pods --namespace default -l app.kubernetes.io/name=nginx-1 | awk 'FNR>1 {print $1}')

      TIMEOUT=60

      for i in ${PODS[@]}; do
        echo "Deleting Pod: $i..."
        kubectl delete pod $i --namespace default
        echo "Sleeping for $TIMEOUT seconds..."
        sleep $TIMEOUT
      done
      ```
  info:
  - name: Nginx External IP
    type: Reference
    valueFrom:
      serviceRef:
        name: nginx-1-nginx-svc
        protocol: HTTPS
  - name: Application Namespace
    value: default
  - name: Nginx Configuration
    value: nginx-config.conf
  - name: Nginx Cert
    type: Reference
    valueFrom:
      secretKeyRef:
        key: https1.cert
        name: nginx-1-nginx-secret
  - name: Nginx Key
    type: Reference
    valueFrom:
      secretKeyRef:
        key: https1.key
        name: nginx-1-nginx-secret
  selector:
    matchLabels:
      app.kubernetes.io/name: "nginx-1"
  componentKinds:
  - group: v1
    kind: ConfigMap
  - group: v1
    kind: PersistentVolumeClaim
  - group: apps/v1
    kind: StatefulSet
  - group: v1
    kind: Secret
  - group: v1
    kind: Service
